#%RAML 1.0
title: "Organizations"
baseUri: https://github.com/folio-org/mod-organizations-storage
version: v1.0

documentation:
  - title: <b>Deprecated.</b> Emails
    content: |
      CRUD APIs used to manage emails.
      <b>These APIs are not currently in use and may at some point be removed or resurrected</b>

types:
    email: !include acq-models/mod-orgs/schemas/email.json
    email_collection: !include acq-models/mod-orgs/schemas/email_collection.json
    errors: !include raml-util/schemas/errors.schema
    UUID:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    language: !include raml-util/traits/language.raml
    validate: !include raml-util/traits/validation.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml


/organizations-storage/emails:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orgs/examples/email_collection.sample
      exampleItem: !include acq-models/mod-orgs/examples/email_post.sample
      schemaCollection: email_collection
      schemaItem: email
  is: [validate]
  get:
    description: Get list of emails
    is: [
      searchable: {description: "with valid searchable fields: for example code", example: "[\"code\", \"MEDGRANT\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a Email
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orgs/examples/email_get.sample
        schema: email
    is: [validate]
