#%RAML 1.0
title: "Integration Details"
baseUri: https://github.com/folio-org/mod-organizations-storage
version: v3.1

documentation:
  - title: Integration Details
    content: <b>CRUD APIs used to manage integration details.</b>

types:
    integration_detail: !include acq-models/mod-orgs/schemas/integration_detail.json
    integration_detail_collection: !include acq-models/mod-orgs/schemas/integration_detail_collection.json
    errors: !include raml-util/schemas/errors.schema
    UUID:
      type: string
      pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
    orderable: !include raml-util/traits/orderable.raml
    pageable:  !include raml-util/traits/pageable.raml
    searchable: !include raml-util/traits/searchable.raml
    validate: !include raml-util/traits/validation.raml

resourceTypes:
    collection: !include raml-util/rtypes/collection.raml
    collection-item: !include raml-util/rtypes/item-collection.raml

/organizations-storage/integration-details:
  type:
    collection:
      exampleCollection: !include acq-models/mod-orgs/examples/integration_detail_collection.sample
      exampleItem: !include acq-models/mod-orgs/examples/integration_detail_post.sample
      schemaCollection: integration_detail_collection
      schemaItem: integration_detail
  is: [validate]
  get:
    description: Get list of integration details
    is: [
      searchable: {description: "with valid searchable fields: for example vendorId", example: "[\"vendorId\", \"f30caa0e-f69b-4555-ba85-34a5754aaad3\", \"=\"]"},
      pageable
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of Integration Detail
        type: UUID
    type:
      collection-item:
        exampleItem: !include acq-models/mod-orgs/examples/integration_detail_get.sample
        schema: integration_detail
    is: [validate]
    put:
      description: Update integration detail with 'export_config_id'
      body:
        application/json:
          example:
            strict: false
            value: !include acq-models/mod-orgs/examples/integration_detail_post.sample
          type: integration_detail
